# Generated by Django 4.2.4 on 2023-11-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_num', models.CharField(max_length=5)),
                ('fiber_len', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='num_of_channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_channel', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='zone_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_num', models.CharField(max_length=5)),
                ('zone_name', models.CharField(max_length=40)),
                ('start_dist', models.CharField(max_length=30)),
                ('end_dist', models.CharField(max_length=30)),
                ('temp_orange_alarm_max', models.CharField(max_length=30)),
                ('temp_orange_alarm_min', models.CharField(max_length=30)),
                ('temp_red_alarm_max', models.CharField(max_length=30)),
                ('temp_red_alarm_min', models.CharField(max_length=30)),
            ],
        ),
    ]
