# Generated by Django 4.2.5 on 2023-11-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts_ver_2_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_fiber', models.CharField(max_length=50000)),
                ('Broken_fiber', models.CharField(max_length=50000)),
                ('temprature_curve_x_axis', models.CharField(max_length=50000)),
                ('temprature_curve_y_axis', models.CharField(max_length=50000)),
            ],
        ),
    ]
