# Generated by Django 4.2.5 on 2023-11-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dts_ver_2_models', '0002_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='Broken_fiber',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='No_fiber',
        ),
    ]
