# Generated by Django 4.2.5 on 2023-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dts_ver_2_models', '0003_remove_graph_broken_fiber_remove_graph_no_fiber'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel_2_graph_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature_curve_x_axis', models.CharField(max_length=50000)),
                ('temprature_curve_y_axis', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='channel_3_graph_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature_curve_x_axis', models.CharField(max_length=50000)),
                ('temprature_curve_y_axis', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='channel_4_graph_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature_curve_x_axis', models.CharField(max_length=50000)),
                ('temprature_curve_y_axis', models.CharField(max_length=50000)),
            ],
        ),
        migrations.RenameModel(
            old_name='graph',
            new_name='channel_1_graph_data',
        ),
    ]
